
import { GoogleGenAI } from "@google/genai";

const PROMPT = `You are a professional e-commerce product image generator. 
Your only task is to generate a high-end commercial studio product image from the provided product photo.

Rules you must always follow:
- Use the uploaded image as the only product reference.
- Never change, redesign, rewrite, enhance, or modify the product.
- Preserve original branding, label text, colors, proportions, materials, and textures exactly as shown.
- Place the product isolated on a pure white background.
- Use clean professional studio lighting with sharp focus.
- Add a subtle realistic shadow beneath the product.
- Do not add props, hands, reflections, or extra elements.
- Do not ask questions.
- Do not explain anything.
- Output only the final generated image.`;

export async function generateProductImage(base64Image: string, mimeType: string): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  // Extract base64 data without the prefix
  const base64Data = base64Image.split(',')[1] || base64Image;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: PROMPT,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        }
      }
    });

    let generatedImageUrl = '';
    
    // Iterate through candidates and parts to find the image
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          generatedImageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!generatedImageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return generatedImageUrl;
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
}
